# For use as a visual studio code cmake plugin "kit" for LLVM+MinGW builds.
SET(CMAKE_C_FLAGS "-target x86_64-pc-windows-gnu" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "-target x86_64-pc-windows-gnu" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_DEBUG "-D_GLIBCXX_DEBUG"  CACHE STRING "" FORCE)
SET(CMAKE_C_COMPILER "clang.exe" CACHE STRING "" FORCE)
SET(CMAKE_CXX_COMPILER "clang++.exe" CACHE STRING "" FORCE)
SET(CMAKE_C_COMPILER_ARCHITECTURE_ID "x64" CACHE STRING "" FORCE)
SET(CMAKE_CXX_COMPILER_ARCHITECTURE_ID "x64" CACHE STRING "" FORCE)
